### ISSUE TITLE
Snapshot issue for Fragment

### ISSUE THREAD

**Issue by Mayank009** [airbnb/enzyme#1735]
Two different snapshots are getting generated using shallow for below component

**Component**:
`import React, { Component, Fragment } from 'react';
<Fragment>
	<Header location={location} matchUrl={match.url} />
	<section className="ps">
		<Switch>
			<Route path={`${matchUrl}/topics`} component={TopicsContainer} />
			<Route path={`${matchUrl}/people`} component={PeopleContainer} />
			<Route path={`${matchUrl}/tools-and-frameworks`} component={ToolsAndFrameworksContainer} />
			<Route path={`${matchUrl}`} component={HomeContainer} />
		</Switch>
	</section>
</Fragment>`

**Snapshot 1**:
`<React.Fragment><Headerlocation={Object {"pathname": "/practices/test_9995",} } matchUrl="/practices/test_9995"/><section className="ps"><Switch><Routecomponent={[Function]}path="/practices/test_9995/topics"/><Routecomponent={[Function]}path="/practices/test_9995/people"/><Routecomponent={[Function]}path="/practices/test_9995/tools-and-frameworks"/><Routecomponent={[Function]}path="/practices/test_9995"/> </Switch></section></React.Fragment>`

**Snapshot 2**:

`<Fragment><Headerlocation={Object {"pathname": "/practices/test_9995",} } matchUrl="/practices/test_9995"/><section className="ps"><Switch><Routecomponent={[Function]}path="/practices/test_9995/topics"/><Routecomponent={[Function]}path="/practices/test_9995/people"/><Routecomponent={[Function]}path="/practices/test_9995/tools-and-frameworks"/><Routecomponent={[Function]}path="/practices/test_9995"/> </Switch></section></Fragment>`

What could be the possible reason for <React.Fragment></React.Fragment> in first and <Fragment></Fragment> in latter for same component?

**Comment by Mayank009** [comment]
When I debugged component for both snapshots I got outputs as below.

Note: I used debug function as below
`const component = shallow(<AppLayout />);`
`component.debug();`

**Snapshot 1**
`<Symbol(react.fragment)><Header location={{...}} matchUrl="/practices/test_9995" /><section className="ps"><Switch><Route path="/practices/test_9995/topics" component={[Function: Connect]} /><Route path="/practices/test_9995/people" component={[Function: Connect]} /><Route path="/practices/test_9995/tools-and-frameworks" component={[Function: Connect]} /><Route path="/practices/test_9995" component={[Function: Connect]} /></Switch></section></Symbol(react.fragment)>`

**Snapshot 2**

`<Fragment><Header location={{...}} matchUrl="/practices/test_9995" /><section className="ps"><Switch><Route path="/practices/test_9995/topics" component={[Function: Connect]} /><Route path="/practices/test_9995/people" component={[Function: Connect]} /><Route path="/practices/test_9995/tools-and-frameworks" component={[Function: Connect]} /><Route path="/practices/test_9995" component={[Function: Connect]} /></Switch></section></Fragment>`

Any help on how can I debug reason for <Symbol(react.fragment)> in first whereas <Fragment> in latter debug output?

**Comment by ljharb** [comment]
Enzyme doesn't actually support snapshots, but you'd indeed want to build snapshot support on top of `.debug()`.

The difference is because the `Symbol(react.fragment)` output was incorrect - and that's now fixed in latest enzyme.

**Comment by Mayank009** [comment]
I upgraded enzyme version to 3.4.1 but still getting Symbol(react.fragment) as name for Fragment in debug. I checked enzyme-to-json code, which I am using to take create tree for snapshot, and they applied a check to fetch the node type.

`export const extractTypeName = node => {
  const name = typeName(node);
  if (name === Symbol.for('react.fragment')) {
    return 'React.Fragment';
  }

  return name;
};`

**Comment by ljharb** [comment]
@Mayank009 have you also updated your react adapter? Make sure both enzyme and your adapter are at latest.

**Comment by Mayank009** [comment]
@ljharb 

"enzyme": "3.4.1",
"enzyme-adapter-react-16": "1.1.1"

**Comment by Mayank009** [comment]
@ljharb fixed after updating version of enzyme-adapter-react-16 to 1.2.0
