### ISSUE TITLE
Child component props aren't updated after call to setState in async handler

### ISSUE THREAD

**Issue by Bargs** [airbnb/enzyme#1872]
I'm having trouble testing an event handler that does an async operation followed by a setState. Even when I wait for the setState to complete by awaiting a promise resolved from inside its callback, the component doesn't seem to fully re-render. What's weird is that I can confirm that the parent state is updated but props on a sub component that rely on that state are not. Even stranger, text that comes from those props inside the sub component is updated like normal.  I created a small script to reproduce the behavior. Note that after the onClick handler and setState finish this child component props are still `{ id: 'childDiv', counter: 1 }`. Only after a forced update do they change.

```jsx
import { mount } from 'enzyme';
import React, { Component } from 'react';
import Promise from 'bluebird';

class TestComponent extends Component {

  state = {
    counter: 1,
  };

  handleClick = async () => {
    await Promise.delay(100);
    return await new Promise((resolve) => {
      this.setState({ counter: 2 }, () => {
        resolve();
      });
    });
  };

  render() {
    return <div id={'parentDiv'} onClick={this.handleClick}>
      <TestSubComponent id={'childDiv'} counter={this.state.counter}/>
    </div>;
  }
}

class TestSubComponent extends Component {

  render() {
    return <div>{this.props.counter}</div>;
  }
}

describe('foo', () => {

  it('should foo', async () => {
    const component = mount(<TestComponent/>);

    // prints {"counter":1}
    console.log('=== parent state before click');
    console.log(JSON.stringify(component.state()));

    // prints { id: 'childDiv', counter: 1 }
    console.log('=== sub component props before click');
    console.log(component.find(TestSubComponent).props());

    // prints 1
    console.log('=== sub component props before click');
    console.log(component.find(TestSubComponent).text());

    await component.find('#parentDiv').props().onClick();

    // prints {"counter":2}
    console.log('=== parent state after click');
    console.log(JSON.stringify(component.state()));

    // prints { id: 'childDiv', counter: 1 }
    console.log('=== sub component props after click');
    console.log(component.find(TestSubComponent).props());

    // prints 2
    console.log('=== sub component text after click');
    console.log(component.find(TestSubComponent).text());

    component.update();

    // prints { id: 'childDiv', counter: 2 }
    console.log('=== sub component props after update');
    console.log(component.find(TestSubComponent).props());

  });

});
```

#### API

- [x] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.7.0
| react               | 16.3.1
| react-dom           | 16.3.1
| react-test-renderer | 16.3.2
| adapter (below)     |  enzyme-adapter-react-16.3@1.3.0

**Comment by ljharb** [comment]
Can you try updating to the latest version of enzyme? we've fixed a lot of bugs since v3.2 (also, you'll need to ensure `react-test-renderer` is also on 16.3 - the minor version must *always* exactly match that of react and react-dom. You may also want to use the 16.3 adapter instead of the generic 16 adapter, altho both should work the same.

**Comment by Bargs** [comment]
Thanks for the response! I tried upgrading to `enzyme` 3.7.0, using `enzyme-adapter-react-16.3` and `react-test-renderer` 16.3.2. Unfortunately, I'm still getting the same test results. I'll update the versions in my original description as well.

**Comment by k3ithl1m** [comment]
@ljharb I would love to help out with Enzyme's open source, How may i help out with this issue

**Comment by ljharb** [comment]
@k3ithl1m submitting a PR with test cases that cover the OP's issue would be great :-)

**Comment by k3ithl1m** [comment]
@ljharb Based on my understanding. Because the functions used like find, text, mount, state and props, are all in ReactWrapper. I will be updating ReactWrapper-spec.jsx with the examples that the OP gave. Correct me if I'm understanding it wrongly.

**Comment by k3ithl1m** [comment]
@ljharb did you mean fixing the bug where calling .props() will also print the right value? So for that case, it would print out 
`// prints { id: 'childDiv', counter: 1 }
    console.log('=== sub component props after click');
    console.log(component.find(TestSubComponent).props());`
I apologize for taking what you said by PR with test cases literally as PR with only test cases. haha

**Comment by ljharb** [comment]
I mean, also including the fix is even better, but the test cases are the most important part.

**Comment by k3ithl1m** [comment]
Okay. Ill make one PR with just the test and then try to work on the fix. Does that sound good?

**Comment by k3ithl1m** [comment]
Can I also install the bluebird module so that its similar to what the OP did? or should I write my own Promise.delay module

**Comment by ljharb** [comment]
definitely not bluebird; something like `function delay(ms) { return new Promise((resolve) => { setTimeout(resolve, ms); }); }` is sufficient
